---

- name: Ensure Elasticsearch apt signing key is installed
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: Install logstash repo from elasticsearch
  apt_repository: repo='deb http://packages.elasticsearch.org/logstash/1.4/debian stable main' state=present

- name: Install logstash
  apt: name=logstash state=present